apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-operator-0.17
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached-operator-0.17
  template:
    metadata:
      labels:
        name: memcached-operator-0.17
    spec:
      serviceAccountName: memcached-operator-0.17
      containers:
        - name: memcached-operator-0.17
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - memcached-operator-0.17
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "memcached-operator-0.17"
